//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary_iBeacon.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class BEACON_ITEMS_ADVERTISEMENT
    {
        public int ID_ITEM { get; set; }
        public string ITEAM_GUID { get; set; }
        public string ITEM_IMG_URL { get; set; }
        public Nullable<int> STRORE_ID { get; set; }
        public Nullable<int> TYPE { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public Nullable<bool> IS_ACTIVE { get; set; }
        public Nullable<int> NUMBER_LIKE { get; set; }
        public Nullable<int> NUMBER_1_STAR { get; set; }
        public Nullable<int> NUMBER_2_STAR { get; set; }
        public Nullable<int> NUMBER_3_STAR { get; set; }
        public Nullable<int> NUMBER_4_STAR { get; set; }
        public Nullable<int> NUMBER_5_STAR { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> PRICE { get; set; }
    }
}
