//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary_iBeacon.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class BEACON_NOTIFICATION
    {
        public int ID { get; set; }
        public string NOTI_GUID { get; set; }
        public string NOTI_MESSAGE { get; set; }
        public string NOTI_WIFI { get; set; }
        public string NOTI_PASSWORD_WIFI { get; set; }
        public Nullable<int> STORE_ID { get; set; }
    }
}
