//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary_iBeacon.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class IBEACON_STORES
    {
        public int ID_STORE { get; set; }
        public string GUID { get; set; }
        public string STORE_NAME { get; set; }
        public int STORE_TYPE_ID { get; set; }
        public int MALL_ID { get; set; }
        public bool BROADCAST_ENABLE { get; set; }
        public string HOME_PAGE { get; set; }
    }
}
