//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary_iBeacon.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class iBeacon_Entities : DbContext
    {
        public iBeacon_Entities()
            : base("name=iBeacon_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BEACON_DEVICES> BEACON_DEVICES { get; set; }
        public virtual DbSet<BEACON_ITEMS_ADVERTISEMENT> BEACON_ITEMS_ADVERTISEMENT { get; set; }
        public virtual DbSet<BEACON_VIDEOS> BEACON_VIDEOS { get; set; }
        public virtual DbSet<IBEACON_STORES> IBEACON_STORES { get; set; }
        public virtual DbSet<MALL> MALLs { get; set; }
        public virtual DbSet<STORE_TYPE> STORE_TYPE { get; set; }
        public virtual DbSet<BEACON_NOTIFICATION> BEACON_NOTIFICATION { get; set; }
    }
}
